name: Screenshot Strava Goals
on:
  issues:
    types: [opened, reopened]

jobs:
  screenshot-strava-goals:
    name: Screenshot Strava Goals
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Take Goals Screenshots
        uses: ./actions/run-puppeteer-script
        with:
          script: ./strava/screenshot-strava-goals.js
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
      - name: Upload As Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: strava-screenshots
          path: ./strava/*.png
      - name: Commit Updated Screenshots
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "(Automated) Updating Strava Goals Snapshot"
